version: '3'

volumes:
  postgresdb:
    driver: local
  pgadmin:
    driver: local

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgresdb:/var/lib/postgresql/data
  postgresgui:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
  traineeapp:
    image: gregorkielbasa/trainee-app
    ports:
      - 8080:8080