CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(24) NOT NULL);
ALTER TABLE PRODUCTS ALTER COLUMN PRODUCT_ID RESTART WITH 100000000;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(16) NOT NULL);
ALTER TABLE CUSTOMERS ALTER COLUMN CUSTOMER_ID RESTART WITH 100000000;

CREATE TABLE IF NOT EXISTS BASKETS (
    CUSTOMER_ID BIGINT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS BASKET_ITEMS (
        BASKET_ID BIGINT NOT NULL,
        PRODUCT_ID BIGINT NOT NULL,
        AMOUNT INT NOT NULL,
        PRIMARY KEY (ORDER_ID, PRODUCT_ID));

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL);
ALTER TABLE ORDERS ALTER COLUMN ORDER_ID RESTART WITH 1000;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID));