apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Change this based on your storage class, e.g., "standard", "gp2", etc.