CREATE SEQUENCE PRODUCT_KEY START WITH 100000000 INCREMENT BY 1;
CREATE SEQUENCE CUSTOMER_KEY START WITH 100000000 INCREMENT BY 1;
CREATE SEQUENCE BASKET_KEY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ORDER_KEY START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(24) NOT NULL);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(16) NOT NULL);

CREATE TABLE IF NOT EXISTS BASKETS (
    BASKET_ID BIGINT  PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS BASKET_ITEMS (
    BASKET_ID BIGINT NOT NULL,
    MAP_KEY BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (BASKET_ID, PRODUCT_ID),
    FOREIGN KEY (BASKET_ID) REFERENCES BASKETS (BASKET_ID));

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID));